services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: employee-app
    ports:
      - "8080:443"
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-local.ini
      - ./docker/apache/app-vhost-ssl.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/certs:/etc/apache2/certs
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes idekey=VSCODE
    depends_on:
      - db

  admin:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: employee-admin
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-local.ini
      - ./docker/apache/admin-vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes idekey=VSCODE
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: employee-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: employee
      MYSQL_USER: employee
      MYSQL_PASSWORD: employee
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
