<?php

const SYSTEM_NAME = "CHIBA CHIKUSAN";

// 権限
const PARAM_CONST_AUTH_LEVEL_NORMAL = 1;
const PARAM_CONST_AUTH_LEVEL_ADMIN = 2;
const PARAM_CONST_AUTH_LEVELS = array(
    PARAM_CONST_AUTH_LEVEL_NORMAL => '一般',
    PARAM_CONST_AUTH_LEVEL_ADMIN => '管理者',
);

// ソート順
const PARAM_CONST_USER_SEARCH_SORT_TYPE_NEW_ENTRY = 1;
const PARAM_CONST_USER_SEARCH_SORT_TYPE_LAST_LOGIN_DATE = 2;
const PARAM_CONST_USER_SEARCH_SORT_TYPES = array(
    PARAM_CONST_USER_SEARCH_SORT_TYPE_NEW_ENTRY => '登録順',
    PARAM_CONST_USER_SEARCH_SORT_TYPE_LAST_LOGIN_DATE => '最終ログイン順',
);

// ソート順
const PARAM_CONST_LOCATION_ASSIGN_USER_SEARCH_SORT_TYPE_NEW_ENTRY = 1;
const PARAM_CONST_LOCATION_ASSIGN_USER_SEARCH_SORT_TYPES = array(
    PARAM_CONST_USER_SEARCH_SORT_TYPE_NEW_ENTRY => '登録順',
);