<?php
/**
 * パラメータ定義
 *
 * @author kanemiya
 */

// サイト名
const SITE_NAME = "千葉県鳥インフル従事者登録";

// 共通のモード
const PARAM_CONST_COMMON_MODE_1 = 1;
const PARAM_CONST_COMMON_MODE_2 = 2;

// ソート種別
const PARAM_CONST_LIST_SORT_ASC = 1;
const PARAM_CONST_LIST_SORT_DESC = 2;

// 従事者ステータス種別
const PARAM_CONST_USER_STATUS_TYPE_ENABLE = 1;
const PARAM_CONST_USER_STATUS_TYPE_DISNABLE = 2;
const PARAM_CONST_USER_STATUS_TYPE_DELETE = 9;
const PARAM_CONST_USER_STATUS_TYPES = array(
	PARAM_CONST_USER_STATUS_TYPE_ENABLE => '有効',
	PARAM_CONST_USER_STATUS_TYPE_DISNABLE => '停止',
	PARAM_CONST_USER_STATUS_TYPE_DELETE => '退会',
);

// 性別種別
const PARAM_CONST_GENDER_TYPE_MALE = 1;
const PARAM_CONST_GENDER_TYPE_FEMALE = 2;
const PARAM_CONST_GENDER_TYPE_NONE = 9;
const PARAM_CONST_GENDER_TYPES = array(
	PARAM_CONST_GENDER_TYPE_MALE => '男性',
	PARAM_CONST_GENDER_TYPE_FEMALE => '女性',
	PARAM_CONST_GENDER_TYPE_NONE => '未指定',
);
const PARAM_CONST_EN_GENDER_TYPES = array(
	PARAM_CONST_GENDER_TYPE_MALE => 'Male',
	PARAM_CONST_GENDER_TYPE_FEMALE => 'Female',
	PARAM_CONST_GENDER_TYPE_NONE => 'none',
);

// 雇用形態種別
const PARAM_CONST_EMPLOY_TYPE_PART = 1;
const PARAM_CONST_EMPLOY_TYPE_DISPATCH = 2;
const PARAM_CONST_EMPLOY_TYPE_SELF = 3;
const PARAM_CONST_EMPLOY_TYPES = array(
	PARAM_CONST_EMPLOY_TYPE_PART => 'アルバイト',
	PARAM_CONST_EMPLOY_TYPE_DISPATCH => '派遣',
	PARAM_CONST_EMPLOY_TYPE_SELF => '個人事業主',
);
const PARAM_CONST_EN_EMPLOY_TYPES = array(
	PARAM_CONST_EMPLOY_TYPE_PART => 'Part-time',
	PARAM_CONST_EMPLOY_TYPE_DISPATCH => 'Dispatch',
	PARAM_CONST_EMPLOY_TYPE_SELF => 'Sole-proprietor',
);

// 証明書種別
const PARAM_CONST_CERT_TYPE_FRONT = 1;
const PARAM_CONST_CERT_TYPE_BACK = 2;
const PARAM_CONST_CERT_TYPES = array(
    PARAM_CONST_CERT_TYPE_FRONT => '表',
    PARAM_CONST_CERT_TYPE_BACK => '裏',
);
const PARAM_CONST_EN_CERT_TYPES = array(
    PARAM_CONST_CERT_TYPE_FRONT => 'Front',
    PARAM_CONST_CERT_TYPE_BACK => 'Back',
);

const PARAM_CONST_USER_APPROVE_TYPE_WAIT = 1;
const PARAM_CONST_USER_APPROVE_TYPE_PASSED = 2;
const PARAM_CONST_USER_APPROVE_TYPE_REJECTED = 3;
const PARAM_CONST_USER_APPROVE_TYPES = array(
    PARAM_CONST_USER_APPROVE_TYPE_WAIT => '承認待ち',
    PARAM_CONST_USER_APPROVE_TYPE_PASSED => '承認済み',
    PARAM_CONST_USER_APPROVE_TYPE_REJECTED => '承認見送り',
);

// 作業シフト予約可能日（n日）
const PARAM_CONST_RESRVE_SHIFT_DAY_FROM = 1; // 1で、翌日から予約可能
const PARAM_CONST_RESRVE_SHIFT_DAY_TO = 14; // 7で、7日後まで予約可能

// シフト種別
const PARAM_CONST_SHIFT_TYPE_A = 1;
const PARAM_CONST_SHIFT_TYPE_B = 2;
const PARAM_CONST_SHIFT_TYPE_C = 3;
const PARAM_CONST_SHIFT_TYPE_D = 4;
const PARAM_CONST_SHIFT_TYPES = array(
    PARAM_CONST_SHIFT_TYPE_A => '日勤(08時-16時)',
    PARAM_CONST_SHIFT_TYPE_B => '準夜(16時-24時)',
    PARAM_CONST_SHIFT_TYPE_C => '夜勤(24時-08時)',
    PARAM_CONST_SHIFT_TYPE_D => '　　常日勤　　',
);

// 性別種別
const PARAM_CONST_SHIFT_ASSIGN_TYPE_IMPOSSIBLE = 1;
const PARAM_CONST_SHIFT_ASSIGN_TYPE_POSSIBLE = 2;
const PARAM_CONST_SHIFT_ASSIGN_TYPE_ASSIGNED = 3;
const PARAM_CONST_SHIFT_ASSIGN_TYPES = array(
	PARAM_CONST_SHIFT_ASSIGN_TYPE_IMPOSSIBLE => 'アサイン不可',
	PARAM_CONST_SHIFT_ASSIGN_TYPE_POSSIBLE => 'アサイン可',
	PARAM_CONST_SHIFT_ASSIGN_TYPE_ASSIGNED => 'アサイン済み',
);

// 記録種別
const PARAM_WORK_TYPE_BEGIN = 1;
const PARAM_WORK_TYPE_END = 2;
const PARAM_WORK_TYPES = array(
	PARAM_WORK_TYPE_BEGIN => '始業',
	PARAM_WORK_TYPE_END => '終業',
);

// 源泉徴収金額種別
const WITHHOLD_TAX_CALC_TYPE_RAGE = 1;
const WITHHOLD_TAX_CALC_TYPE_RATIO = 2;
const WITHHOLD_TAX_CALC_TYPES = array(
	WITHHOLD_TAX_CALC_TYPE_RAGE => '範囲',
	WITHHOLD_TAX_CALC_TYPE_RATIO => '割合',
);

// 言語種別
const PARAM_CONST_LANG_TYPE_JP = 1;
const PARAM_CONST_LANG_TYPE_EN = 2;
const PARAM_CONST_LANG_TYPES = array(
	PARAM_CONST_LANG_TYPE_JP => '日本語',
	PARAM_CONST_LANG_TYPE_EN => '英語',
);
const PARAM_CONST_EN_LANG_TYPES = array(
	PARAM_CONST_LANG_TYPE_JP => 'Japanese',
	PARAM_CONST_LANG_TYPE_EN => 'English',
);
const PARAM_CONST_ALL_LANG_TYPES = array(
	PARAM_CONST_LANG_TYPE_JP => '日本語 / Japanese',
	PARAM_CONST_LANG_TYPE_EN => '英語 / English',
);
